import OCAPI, { Util } from "sfcc-ocapi-documents";

export const productItem: Util.Typed<OCAPI.ProductItem> = {
  _type: "product_item",
  adjusted_tax: 15.16,
  base_price: 94.95,
  bonus_product_line_item: false,
  gift: false,
  item_id: "3fcfee1726131b23d69e11f2f9",
  item_text: "item text",
  option_items: [],
  price: 94.95,
  price_after_item_discount: 94.95,
  price_after_order_discount: 94.95,
  product_id: "DD1234_55",
  product_name: "product name",
  quantity: 1,
  shipment_id: "me",
  tax: 15.16,
  tax_basis: 94.95,
  tax_class_id: "FullTax",
  tax_rate: 0.19,
  c_customAttribute: "custom data",
};

export const another: Util.Typed<OCAPI.ProductItem> = {
  _type: "product_item",
  adjusted_tax: 15.16,
  base_price: 94.95,
  bonus_product_line_item: false,
  gift: false,
  item_id: "bca7979bc7b9cca79b7",
  item_text: "product name",
  option_items: [
    {
      _type: "option_item",
      adjusted_tax: 0.0,
      base_price: 0.0,
      bonus_product_line_item: false,
      gift: false,
      item_id: "bca45bac67ac8bca8cba9cababc90",
      item_text: "Test testing",
      option_id: "someOptionId",
      option_value_id: "NP",
      price: 0.0,
      price_after_item_discount: 0.0,
      price_after_order_discount: 0.0,
      product_id: "_NP",
      product_name: "Test product name",
      quantity: 1,
      shipment_id: "me",
      tax: 0.0,
      tax_basis: 0.0,
      tax_class_id: "FullTax",
      tax_rate: 0.19,
    },
    {
      _type: "option_item",
      adjusted_tax: 0.0,
      base_price: 0.0,
      bonus_product_line_item: false,
      gift: false,
      item_id: "4b7df75f1cdbe3bd37dae63267",
      item_text: "Test item text",
      option_id: "someOtherOptionId",
      option_value_id: "NP",
      price: 0.0,
      price_after_item_discount: 0.0,
      price_after_order_discount: 0.0,
      product_id: "_NP",
      product_name: "Test product name",
      quantity: 1,
      shipment_id: "me",
      tax: 0.0,
      tax_basis: 0.0,
      tax_class_id: "FullTax",
      tax_rate: 0.19,
    },
  ],
  price: 94.95,
  price_after_item_discount: 94.95,
  price_after_order_discount: 94.95,
  product_id: "M-992",
  product_name: "productname",
  quantity: 1,
  shipment_id: "me",
  tax: 15.16,
  tax_basis: 94.95,
  tax_class_id: "FullTax",
  tax_rate: 0.19,
  c_customAttribute: "data",
};
