import Previous from "../20.8";

namespace SFCC {
  export type CouponItem = Previous.CouponItem;
  export type GiftCertificate = Previous.GiftCertificate;
  export type OptionItem = Previous.OptionItem;
  export type ProductDetailsLink = Previous.ProductDetailsLink;
  export type Recommendation = Previous.Recommendation;
  export type Taxation = Previous.Taxation;
  export type Customer = Previous.Customer;
  export type GiftCertificateItem = Previous.GiftCertificateItem;
  export type OptionValue = Previous.OptionValue;
  export type ProductItem = Previous.ProductItem;
  export type RecommendationType = Previous.RecommendationType;
  export type Variant = Previous.Variant;
  export type ApproachingDiscount = Previous.ApproachingDiscount;
  export type CustomerAddress = Previous.CustomerAddress;
  export type Image = Previous.Image;
  export type Order = Previous.Order;
  export type ProductLink = Previous.ProductLink;
  export type Shipment = Previous.Shipment;
  export type VariationAttribute = Previous.VariationAttribute;
  export type Basket = Previous.Basket;
  export type CustomerInfo = Previous.CustomerInfo;
  export type ImageGroup = Previous.ImageGroup;
  export type OrderAddress = Previous.OrderAddress;
  export type ProductListItemReference = Previous.ProductListItemReference;
  export type ShippingItem = Previous.ShippingItem;
  export type VariationAttributeValue = Previous.VariationAttributeValue;
  export type BonusDiscountLineItem = Previous.BonusDiscountLineItem;
  export type CustomerPaymentInstrument = Previous.CustomerPaymentInstrument;
  export type Inventory = Previous.Inventory;
  export type OrderPaymentInstrument = Previous.OrderPaymentInstrument;
  export type ProductListLink = Previous.ProductListLink;
  export type ShippingMethod = Previous.ShippingMethod;
  export type VariationGroup = Previous.VariationGroup;
  export type BundledProduct = Previous.BundledProduct;
  export type Discount = Previous.Discount;
  export type Localized = Previous.Localized;
  export type PathRecord = Previous.PathRecord;
  export type ProductPromotion = Previous.ProductPromotion;
  export type ShippingPromotion = Previous.ShippingPromotion;
  export type Category = Previous.Category;
  export type Fault = Previous.Fault;
  export type Master = Previous.Master;
  export type PriceAdjustment = Previous.PriceAdjustment;
  export type ProductType = Previous.ProductType;
  export type SimpleLink = Previous.SimpleLink;
  export type ChannelType = Previous.ChannelType;
  export type Flash = Previous.Flash;
  export type Option = Previous.Option;
  export type Product = Previous.Product;
  export type PromotionLink = Previous.PromotionLink;
  export type SiteSpecific = Previous.SiteSpecific;
  export { CustomersExtProfile } from "./CustomersExtProfile";
}

export default SFCC;
