export type ChannelType =
  | "storefront"
  | "callcenter"
  | "marketplace"
  | "dss"
  | "store"
  | "pinterest"
  | "twitter"
  | "facebookads"
  | "subscriptions"
  | "onlinereservation"
  | "customerservicecenter"
  | "instagramcommerce"
